services:
  - type: web
    name: cotton-plant-disease
    env: python
    pythonVersion: 3.11.9
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py --server.port=$PORT --server.address=0.0.0.0"
